version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:BroytPGDB123!!@db:5432/ChalkboardDemo"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
