version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:BroytPGDB123!!@db:5432/ChalkboardDemo"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=BroytPGDB123!!
      - POSTGRES_DB=ChalkboardDemo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
