version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
